hw2
================
2026-09-30

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

\#Problem 1

## Data cleaning attempt

``` r
subway_df = 
  read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv", na = c("")) |>
  janitor::clean_names() |>
  mutate(
    
    staffing = case_when(
      staffing == "PART" & !is.na(staff_hours) ~ staff_hours,
      TRUE ~ staffing
    ),
    
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE,
      .default = NA
    ),
    
    vending = case_match(
      vending,
      "YES" ~ TRUE,
      "NO" ~ FALSE,
      .default = NA
    ),
    
    across(
      route1:route11,
      ~ replace_na(as.character(.x), "_")
    )
    
  ) |>
  unite(
    routes_served,
    route1:route11,
    sep = "|",
    remove = TRUE
  ) |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    routes_served,
    entry,
    vending,
    staffing,
    entrance_type,
    ada
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE, .default
    ##   = NA)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
stations_df = subway_df |>
  group_by(
    line,
    station_name
  ) |>
  summarise(
    routes_served = first(routes_served),
    ada_compliant = any(ada, na.rm = TRUE),
    number_of_entrances = n(),
    .groups = "drop"
  )
```

## Questions answering

``` r
# Distinct stations
distinct_stations_num = stations_df |>
  distinct(line,station_name) |>
  nrow()

distinct_stations_num
```

    ## [1] 465

``` r
# ADA compliant

subway_df |>
  filter(ada == TRUE) |>
  distinct(line,station_name) |>
  nrow()
```

    ## [1] 84

``` r
# Proportion without vending allow entrance
subway_df |>
  filter(!vending) |>
  summarise(
    total_no_vending = n(),
    allow_entrance = sum(entry,na.rm = TRUE),
    proportion = allow_entrance / total_no_vending
  )
```

    ## # A tibble: 1 × 3
    ##   total_no_vending allow_entrance proportion
    ##              <int>          <int>      <dbl>
    ## 1              183             69      0.377

# Problem 2

## Data import

``` r
#mr.trash
mr_trash = 
  read_excel(
  "202610 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N709"
  ) |>
  janitor::clean_names() |>
  mutate(
    trash_wheel = "Mr. Trash Wheel",
    sports_balls = as.integer(round(sports_balls)),
    year = as.numeric(year)
  ) |>
  filter(!is.na(dumpster))

mr_trash
```

    ## # A tibble: 707 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 697 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

``` r
#professor_trash
professor_trash = 
  read_excel(
  "202610 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M134"
  ) |>
  janitor::clean_names() |>
  mutate(
    trash_wheel = "Professor Trash Wheel"
  ) |>
  filter(!is.na(dumpster))

professor_trash
```

    ## # A tibble: 132 × 14
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 122 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

``` r
#Gwynns Falls trash
gwynnda = 
  read_excel(
  "202610 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda the Good Wheel of the W",
  range = "A2:L351"
  ) |>
  janitor::clean_names() |>
  mutate(
    trash_wheel = "Gwynnda"
  ) |>
  filter(!is.na(dumpster))

gwynnda
```

    ## # A tibble: 349 × 13
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 339 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

# combine

``` r
trash_wheel = bind_rows(
  mr_trash,
  professor_trash,
  gwynnda
)

trash_wheel
```

    ## # A tibble: 1,188 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

The dataset we gain here is basically a combined version of three
trashes’ datasets with 1188 rows and 15 features. Each row represents a
dumpster collection either from Mr. Trash Wheel, Professor Trash Wheel,
or Gwynnda, identified by the `trash_wheel` variable. Key variables
include collection date, dumpster number, weight of trash in tons,
volume in cubic yards, and counts of different types of trash such as
plastic bottles, cigarette butts, plastic bags, and food wrappers.

# some calculations

``` r
trash_wheel |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarise(
    total_weight = sum(weight_tons, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         282.

``` r
trash_wheel |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarise(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_cigarette_butts
    ##                   <dbl>
    ## 1                 18120

Specifically, Professor Trash Wheel collected a total of 3637.57 tons of
trash. In June 2022, Gwynnda collected a total of 1.4575698^{7}
cigarette butts.

# Problem3

``` r
# Baseline cleaning
mci_baseline = read_csv("data_mci/MCI_baseline.csv", skip = 2,
  col_names = c(
    "id",
    "baseline_age",
    "sex",
    "education",
    "apoe4",
    "mci_onset_age"
  ),
  na = "."
  ) |>
  mutate(
    sex = case_match(
      sex,
      0 ~ "Female",
      1 ~ "Male"
    ),
    apoe4 = case_match(
      apoe4,
      0 ~ "Non-carrier",
      1 ~ "Carrier"
    ),
    sex = factor(sex),
    apoe4 = factor(apoe4)
  ) |>
  filter(
    is.na(mci_onset_age) |
      mci_onset_age > baseline_age
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): id, baseline_age, sex, education, apoe4, mci_onset_age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# Baseline summaries
mci_baseline |>
  summarise(
    participants = n(),
    developed_mci = sum(!is.na(mci_onset_age)),
    average_baseline_age = mean(baseline_age)
  )
```

    ## # A tibble: 1 × 3
    ##   participants developed_mci average_baseline_age
    ##          <int>         <int>                <dbl>
    ## 1          479            93                 65.0

``` r
mci_baseline |>
  filter(sex == "Female") |>
  summarise(
    women = n(),
    apoe4_carriers = sum(apoe4 == "Carrier"),
    proportion_carriers =
      mean(apoe4 == "Carrier")
  )
```

    ## # A tibble: 1 × 3
    ##   women apoe4_carriers proportion_carriers
    ##   <int>          <int>               <dbl>
    ## 1   210             63                 0.3

The baseline dataset was cleaned by recoding sex and APOE4 carrier
status as categorical variables and removing participants who already
had MCI at baseline. The cleaned dataset contains 479 participants, of
whom 93 developed MCI during follow-up. The average baseline age was
65.029 years, and the proportion of women who were APOE4 carriers was
0.3000.

``` r
# Amyloid data
mci_amyloid = read_csv("data_mci/mci_amyloid.csv", skip = 2,
  col_names = c(
    "id",
    "baseline",
    "time_2",
    "time_4",
    "time_6",
    "time_8"
  )
) |>
  pivot_longer(
    cols = baseline:time_8,
    names_to = "visit",
    values_to = "amyloid_42_40"
  ) |>
  mutate(
    visit = case_match(
      visit,
      "baseline" ~ 0,
      "time_2" ~ 2,
      "time_4" ~ 4,
      "time_6" ~ 6,
      "time_8" ~ 8
    )
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): baseline, time_2, time_4, time_6, time_8
    ## dbl (1): id
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The amyloid dataset was reshaped from wide to long format so that each
row represents one participant at one study visit. It contains 487
participants and 2435 participant-visit observations, with some
biomarker values missing across visits.

``` r
# Participants appearing in only one dataset
baseline_only = mci_baseline |>
  anti_join(
    mci_amyloid |> distinct(id),
    by = "id"
  )

amyloid_only = mci_amyloid |>
  distinct(id) |>
  anti_join(
    mci_baseline,
    by = "id"
  )

# Combine datasets
mci_complete = mci_amyloid |>
  inner_join(
    mci_baseline,
    by = "id"
  )

# Export
write_csv(
  mci_complete,
  "data_mci/mci_complete.csv"
)
```

There were 8 participants found only in the cleaned baseline dataset and
16 IDs found only in the amyloid dataset. After using an inner join to
retain participants present in both datasets, the combined dataset
contains 471 participants and 2355 participant-visit observations.
